# Generated by Django 5.0.4 on 2026-07-21 18:08

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Bookmark',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='EligibilityCheck',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('result', models.CharField(choices=[('eligible', 'Eligible'), ('not_eligible', 'Not Eligible'), ('needs_info', 'Needs More Information')], max_length=20)),
                ('explanation', models.JSONField(default=list, help_text='List of condition results explaining the decision')),
                ('checked_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'ordering': ['-checked_at'],
            },
        ),
        migrations.CreateModel(
            name='Scheme',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('description', models.TextField()),
                ('category', models.CharField(choices=[('Agriculture', 'Agriculture'), ('Education', 'Education'), ('Health', 'Health'), ('Housing', 'Housing'), ('Women', 'Women'), ('Employment', 'Employment'), ('Finance', 'Finance'), ('Insurance', 'Insurance'), ('Pension', 'Pension'), ('MSME', 'MSME'), ('Other', 'Other')], max_length=100)),
                ('state_applicable', models.CharField(default='All', max_length=100)),
                ('benefits', models.TextField(help_text='Description of financial or other benefits')),
                ('documents_required', models.TextField(help_text='Comma-separated list of required documents')),
                ('official_website', models.URLField(blank=True, null=True)),
                ('deadline', models.DateField(blank=True, null=True)),
                ('is_active', models.BooleanField(default=True)),
                ('search_tags', models.TextField(blank=True, help_text='Space-separated keywords for search')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='SchemeRule',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('logic', models.JSONField(help_text='JSON Logic rule for eligibility')),
            ],
        ),
    ]
