# Generated by Django 5.0.4 on 2026-07-21 18:08

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('schemes', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='bookmark',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='bookmarks', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='eligibilitycheck',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='eligibility_checks', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='eligibilitycheck',
            name='scheme',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='eligibility_checks', to='schemes.scheme'),
        ),
        migrations.AddField(
            model_name='bookmark',
            name='scheme',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='bookmarks', to='schemes.scheme'),
        ),
        migrations.AddField(
            model_name='schemerule',
            name='scheme',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='rule', to='schemes.scheme'),
        ),
        migrations.AlterUniqueTogether(
            name='bookmark',
            unique_together={('user', 'scheme')},
        ),
    ]
