# Generated by Django 5.0.4 on 2026-07-21 18:15

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='CitizenProfile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('age', models.IntegerField(blank=True, null=True)),
                ('gender', models.CharField(blank=True, choices=[('Male', 'Male'), ('Female', 'Female'), ('Other', 'Other')], max_length=20, null=True)),
                ('state', models.CharField(blank=True, max_length=100, null=True)),
                ('district', models.CharField(blank=True, max_length=100, null=True)),
                ('annual_income', models.DecimalField(blank=True, decimal_places=2, max_digits=12, null=True)),
                ('occupation', models.CharField(blank=True, max_length=100, null=True)),
                ('education', models.CharField(blank=True, max_length=100, null=True)),
                ('category', models.CharField(blank=True, choices=[('SC', 'SC'), ('ST', 'ST'), ('OBC', 'OBC'), ('General', 'General')], max_length=20, null=True)),
                ('disability_status', models.BooleanField(default=False)),
                ('marital_status', models.CharField(blank=True, max_length=50, null=True)),
                ('family_size', models.IntegerField(blank=True, null=True)),
                ('is_rural', models.BooleanField(default=False, help_text='True if rural, False if urban')),
                ('land_ownership_acres', models.DecimalField(blank=True, decimal_places=2, max_digits=8, null=True)),
                ('is_student', models.BooleanField(default=False)),
                ('employment_status', models.CharField(blank=True, max_length=50, null=True)),
                ('extra_details', models.JSONField(blank=True, default=dict)),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='profile', to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
